API assignment first
tejashrighogare/APITestingAsssignment pull request #1
Opened 2023-04-21 07:27 UTC by tejashrighogare

2023-04-21 07:43 UTC, vrushalee123 requested changes

2023-04-21 07:43 UTC, vrushalee123 commented on src/test/java/APIAssignment/APIAssignmentGet.java
> +import io.restassured.*;
Please make it maven project. I can't see pom.xml

2023-04-21 07:43 UTC, vrushalee123 commented on src/test/java/APIAssignment/APIAssignmentGet.java
> +        System.out.println("status code is "+statusCodeValue);
Remove sysouts

2023-04-21 07:43 UTC, vrushalee123 commented on src/test/java/APIAssignment/APIAssignmentGet.java
> +        var getALLProductList = given().when().get(productListURL).then().log().all().toString();
Validate content

2023-04-21 07:53 UTC, pooja-hasure commented on src/test/java/APIAssignment/APIAssignmentGet.java
> +        Response response = specification.request(Method.GET);
You can add Query or path parameter to get the particular response  on line no.23

2023-04-21 07:53 UTC, pooja-hasure commented on src/test/java/APIAssignment/APIAssignmentGet.java
> +        Assert.assertEquals(bodyContent.contains("name"), true);
You can first verify the status code and status line.

2023-04-21 08:03 UTC, tejashrighogare commented on src/test/java/APIAssignment/APIAssignmentGet.java
> +        System.out.println("status code is "+statusCodeValue);
I will remove

2023-04-21 08:03 UTC, tejashrighogare commented on src/test/java/APIAssignment/APIAssignmentGet.java
> +        var getALLProductList = given().when().get(productListURL).then().log().all().toString();
Okay

2023-04-25 09:23 UTC, vrushalee123 requested changes

2023-04-25 09:23 UTC, vrushalee123 commented on src/test/java/APIAssignment/APIAssignmentGet.java
> +        var productName = response.jsonPath().get("products[3].name").toString();
Don't use hard coded index value.

2023-04-25 09:23 UTC, vrushalee123 commented on src/test/java/APIAssignment/APIAssignmentGet.java
> +        Assert.assertEquals(productPrice, "Rs. 1500");
Write code to validate all contents.

2023-04-25 10:26 UTC, amitsahu8 requested changes

2023-04-25 10:26 UTC, amitsahu8 commented on src/test/java/dataProvider/ConfigReader.java
> +        } catch (FileNotFoundException exception) {
use or in Catch

2023-04-25 10:26 UTC, amitsahu8 commented on src/test/java/dataProvider/ConfigReader.java
> +        String configFilePath = "src\\test\\ConfigProperties\\configuration.properties";
don't hard code the path, use System.getProperty("user.dir")

2023-04-25 10:26 UTC, amitsahu8 commented on src/test/java/dataProvider/ConfigReader.java
> +        FileInputStream fileStream = null;
why FileInputStream declared here?

2023-05-02 07:12 UTC, amitsahu8 requested changes

2023-05-02 07:12 UTC, amitsahu8 commented on src/test/java/APIAssignment/APIAssignmentGet.java
> +        for (var counter = 0; counter < productsArray.toString().length(); counter++) {
use lambda function

2023-05-02 07:12 UTC, amitsahu8 commented on src/test/java/APIAssignment/APIAssignmentGet.java
> +    private Logger logger = Logger.getLogger(APIAssignmentGet.class.getName());
why .getName()?

2023-05-08 13:24 UTC, amitsahu8 requested changes

2023-05-08 13:24 UTC, amitsahu8 commented on src/test/java/APIAssignment/Product.java
> +        productId = productListId;
use getter setter to set and get the values

2023-05-08 13:24 UTC, amitsahu8 commented on src/main/java/dataProvider/ConfigReader.java
> +        try {
remove extra spaces and use or operator to combine the catch

2023-05-10 06:51 UTC, amitsahu8 requested changes

2023-05-10 06:51 UTC, amitsahu8 commented on src/test/java/APIAssignment/Product.java
> +        System.out.println("Id=" + productId);
Use logger instead of sysout and in getter return the variable

2023-05-12 09:20 UTC, amitsahu8 approved these changes

2023-05-29 09:54 UTC, vrushalee123 requested changes

2023-05-29 09:54 UTC, vrushalee123 commented on src/main/java/dataProvider/ConfigReader.java
> +        } catch (Exception e) {
Change exception to specific expression and use logger to print errors properly.

2023-05-29 11:25 UTC, vrushalee123 requested changes
Please do proper formatting.

2023-05-29 11:25 UTC, vrushalee123 commented on src/main/java/dataProvider/ConfigReader.java
> +
Remove extra space. Please do proper indentation.

2023-05-30 08:13 UTC, vrushalee123 requested changes

2023-05-30 08:13 UTC, vrushalee123 commented on src/main/java/dataProvider/ConfigReader.java
> +        } catch (Exception FileNotFoundException) {
Why two exceptions

2023-05-30 08:13 UTC, vrushalee123 commented on src/main/java/dataProvider/ConfigReader.java
> +        } catch (Exception FileNotFoundException) {
Please make it FileNotFoundException

2023-05-30 09:28 UTC, vrushalee123 approved these changes

2023-05-30 09:28 UTC, merged